[package]
name = "alpha-evolve"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { workspace = true }
num-traits = { workspace = true }
num-integer = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
factoring-core = { path = "../factoring-core" }
